networks: 
  phpinfo-2:
    internal: true
services:
  phpinfo-2:
    deploy:
      #varios conenedores en la misma VM
      mode: replicated
      #un unico contenedor por cada VM
      #mode : global
      placemente: 
        constraints:
        - node.role == worker
      replicas: 2
      resources: 
        limits:
          cpus: "0.1"
          memory: 100m
        reservetions:
          cpus: "0.1"
          memory: 100m
      expose:
      - 8080 
      healthchek:
        internal: 20s
        retries: 3
        start_period: 10s
        #test: php -r "print file_get_contents('http://localhost:8080/');"
        test: wget -q --spider http://localhost:8080
        timeout: 10s
      image: ljferrero/phpinfo-2:latest
      networks:
      - phpinfo-2
      ports:
      - 8080:8080
version : "3.8"

